plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow'
}

base {
    archivesName = "$rootProject.archives_name-bluemap-addon"
}

repositories {
    mavenCentral()
    maven { url "https://repo.bluecolored.de/releases" }
}

dependencies {
    implementation project(':common')
    
    // BlueMap API
    compileOnly 'de.bluecolored.bluemap:BlueMapAPI:2.9.0'
    
    // Required for addon
    implementation 'com.google.code.gson:gson:2.10.1'
    compileOnly 'org.projectlombok:lombok:1.18.38'
    annotationProcessor 'org.projectlombok:lombok:1.18.38'
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

shadowJar {
    archiveClassifier = ''
    configurations = [project.configurations.runtimeClasspath]
    
    // Don't include BlueMap API in the final jar
    dependencies {
        exclude(dependency('de.bluecolored.bluemap:BlueMapAPI'))
    }
}

tasks.named('build') {
    dependsOn shadowJar
}
